"""A* path planning for a hopping robot on a 2.5D grid map.

Instead of stepping to one of 8 adjacent cells, the robot hops to points on
a circle of radius `hop_radius` around its current position. Neighbors are
generated by sampling `n_angles` evenly spaced directions on that circle and
snapping each candidate landing point to the underlying grid.
"""

import heapq
import numpy as np

from map2d5 import Map2D5


class HoppingAStarPlanner:
    """A* planner for a hopping robot on a 2.5D grid map.

    Every expansion generates candidate landing cells by sampling `n_angles`
    evenly spaced points on a circle of radius `hop_radius` around the current
    cell. A hop is accepted only when:
      * the landing cell is inside the map and is not marked as an obstacle,
      * the elevation change |z_land - z_start| is within `max_jump_height`,
      * every intermediate cell along the hop line has elevation no more than
        `max_jump_height` above the takeoff (so tall terrain acts as a wall,
        while short bumps can be flown over and landed on).

    A "goal-snap" edge is added whenever the goal lies within `hop_radius` of
    the current cell, so the planner can land exactly on the goal without
    needing a ring sample to happen to align with it.
    """

    def __init__(
        self,
        map_env: Map2D5,
        start: tuple[float, float],
        goal: tuple[float, float],
        hop_radius: float,
        n_angles: int = 16,
        max_jump_height: float = 0.5,
        alpha_uphill: float = 1.0,
        alpha_downhill: float = 0.5,
    ):
        self.map_env = map_env
        self.start_world = start
        self.goal_world = goal
        self.hop_radius = hop_radius
        self.n_angles = n_angles
        self.max_jump_height = max_jump_height
        self.alpha_uphill = alpha_uphill
        self.alpha_downhill = alpha_downhill

        # Convert start/goal to grid coordinates
        self.start_cell = map_env.world_to_grid(start[0], start[1])
        self.goal_cell = map_env.world_to_grid(goal[0], goal[1])

        # Precompute unit-vector directions for ring sampling
        angles = np.linspace(0.0, 2.0 * np.pi, n_angles, endpoint=False)
        self._hop_dirs = [(float(np.cos(a)), float(np.sin(a))) for a in angles]

    def plan(self) -> list[tuple[float, float]] | None:
        """Run A* and return the path as a list of (x, y) world coords, or None."""
        start = self.start_cell
        goal = self.goal_cell

        # Priority queue: (f_cost, counter, (row, col))
        open_set = []
        counter = 0
        heapq.heappush(open_set, (0.0, counter, start))

        # g_cost[cell] = best known cost from start to cell
        g_cost = {start: 0.0}
        # came_from[cell] = parent cell
        came_from: dict[tuple[int, int], tuple[int, int] | None] = {start: None}

        while open_set:
            f, _, current = heapq.heappop(open_set)

            if current == goal:
                return self._reconstruct_path(came_from, current)

            # Skip if we've already found a better path to this node
            if f > g_cost.get(current, float("inf")) + self._heuristic(current):
                continue

            for neighbor, edge_cost in self._generate_hop_neighbors(current):
                tentative_g = g_cost[current] + edge_cost

                if tentative_g < g_cost.get(neighbor, float("inf")):
                    g_cost[neighbor] = tentative_g
                    came_from[neighbor] = current
                    f_cost = tentative_g + self._heuristic(neighbor)
                    counter += 1
                    heapq.heappush(open_set, (f_cost, counter, neighbor))

        return None  # No path found

    def _generate_hop_neighbors(
        self,
        current: tuple[int, int],
    ) -> list[tuple[tuple[int, int], float]]:
        """Yield (neighbor_cell, edge_cost) pairs reachable from `current` in one hop.

        Neighbors are grid cells whose centers are ~hop_radius away in xy,
        found by sampling `n_angles` directions on the ring. A "goal-snap"
        edge is also added when the goal lies within hop_radius, so the goal
        can be landed on exactly regardless of angular alignment.
        """
        cx, cy = self.map_env.grid_to_world(current[0], current[1])
        current_z = self.map_env.grid[current[0], current[1]]

        results: list[tuple[tuple[int, int], float]] = []
        seen: set[tuple[int, int]] = {current}

        # Ring samples at radius = hop_radius
        for dx, dy in self._hop_dirs:
            tx = cx + self.hop_radius * dx
            ty = cy + self.hop_radius * dy

            # Reject candidates outside the map
            if not self.map_env.is_within_bounds(tx, ty):
                continue

            neighbor = self.map_env.world_to_grid(tx, ty)
            if neighbor in seen:
                continue
            seen.add(neighbor)

            edge = self._validate_and_cost(current, current_z, neighbor)
            if edge is not None:
                results.append((neighbor, edge))

        # Goal-snap edge: allow landing exactly on the goal when it's in range
        gx, gy = self.map_env.grid_to_world(self.goal_cell[0], self.goal_cell[1])
        if np.hypot(gx - cx, gy - cy) <= self.hop_radius and self.goal_cell not in seen:
            edge = self._validate_and_cost(current, current_z, self.goal_cell)
            if edge is not None:
                results.append((self.goal_cell, edge))

        return results

    def _validate_and_cost(
        self,
        current: tuple[int, int],
        current_z: float,
        neighbor: tuple[int, int],
    ) -> float | None:
        """Return edge cost if the hop is valid, else None."""
        neighbor_z = self.map_env.grid[neighbor[0], neighbor[1]]

        # Landing must not be on an obstacle
        if neighbor_z == Map2D5.OBSTACLE:
            return None

        # Hard jump height constraint on landing
        dz = neighbor_z - current_z
        if abs(dz) > self.max_jump_height:
            return None

        # Arc-clearance: intermediate terrain taller than what the robot can
        # clear from takeoff blocks the hop (acts as a wall).
        if not self._arc_is_clear(current, neighbor, current_z):
            return None

        return self._edge_cost(current, neighbor, dz)

    def _arc_is_clear(
        self,
        current: tuple[int, int],
        neighbor: tuple[int, int],
        current_z: float,
    ) -> bool:
        """Return True if no intermediate cell on the hop line is too tall.

        An intermediate cell blocks the hop when its elevation exceeds
        `current_z + max_jump_height`. The takeoff and landing cells are
        excluded (they are validated separately). Samples are taken at half a
        cell resolution so every cell the straight line passes through is
        checked at least once. Cells marked as OBSTACLE (z = -1) are treated
        as flyable (holes rather than walls).
        """
        cx, cy = self.map_env.grid_to_world(current[0], current[1])
        nx, ny = self.map_env.grid_to_world(neighbor[0], neighbor[1])

        hop_len = float(np.hypot(nx - cx, ny - cy))
        if hop_len == 0.0:
            return True

        step = self.map_env.resolution * 0.5
        n_samples = max(2, int(np.ceil(hop_len / step)) + 1)
        max_clearable = current_z + self.max_jump_height
        checked: set[tuple[int, int]] = {current, neighbor}

        for i in range(1, n_samples - 1):  # skip endpoints
            t = i / (n_samples - 1)
            sx = cx + t * (nx - cx)
            sy = cy + t * (ny - cy)
            if not self.map_env.is_within_bounds(sx, sy):
                continue
            cell = self.map_env.world_to_grid(sx, sy)
            if cell in checked:
                continue
            checked.add(cell)
            cell_z = self.map_env.grid[cell[0], cell[1]]
            if cell_z != Map2D5.OBSTACLE and cell_z > max_clearable:
                return False
        return True

    def _edge_cost(
        self,
        current: tuple[int, int],
        neighbor: tuple[int, int],
        dz: float,
    ) -> float:
        """Cost of hopping from `current` to `neighbor`.

        Cost = actual Euclidean xy-distance between cell centers + elevation
        penalty (asymmetric: uphill and downhill weighted differently).
        """
        cx, cy = self.map_env.grid_to_world(current[0], current[1])
        nx, ny = self.map_env.grid_to_world(neighbor[0], neighbor[1])
        xy_dist = float(np.hypot(nx - cx, ny - cy))

        if dz > 0:
            elevation_penalty = self.alpha_uphill * dz
        elif dz < 0:
            elevation_penalty = self.alpha_downhill * abs(dz)
        else:
            elevation_penalty = 0.0

        return xy_dist + elevation_penalty

    def _heuristic(self, cell: tuple[int, int]) -> float:
        """Admissible heuristic: Euclidean distance in world coordinates to goal.

        Admissible because sum of hop xy-distances >= straight-line distance
        (triangle inequality), and elevation only adds cost.
        """
        x1, y1 = self.map_env.grid_to_world(cell[0], cell[1])
        x2, y2 = self.map_env.grid_to_world(self.goal_cell[0], self.goal_cell[1])
        return float(np.hypot(x1 - x2, y1 - y2))

    def _reconstruct_path(
        self,
        came_from: dict[tuple[int, int], tuple[int, int] | None],
        current: tuple[int, int],
    ) -> list[tuple[float, float]]:
        """Trace back from goal to start, return path in world coordinates."""
        path_cells = []
        while current is not None:
            path_cells.append(current)
            current = came_from[current]
        path_cells.reverse()

        path = []
        for row, col in path_cells:
            x, y = self.map_env.grid_to_world(row, col)
            path.append((x, y))
        return path
