"""A* path planning for a hopping robot on a 2.5D grid map.

Instead of stepping to one of 8 adjacent cells, the robot hops to points on
a circle around its current position. The circle's radius is not a tuned
constant: it is the flat-ground 45-degree ballistic range the robot's
*current* energy state affords (see `max_hop_radius`), so it shrinks and
grows with the speed the robot arrives at each state. Neighbors are
generated by filling that circle with a `hop_scan_step`-spaced lattice (a
scanline circle fill — every point lies inside the disk by construction,
spacing widening for large radii to keep candidate count near-linear rather
than quadratic in the radius — see `_generate_hop_neighbors`) and snapping
each candidate landing point to the underlying grid.

Hop feasibility and cost use a ballistic (parabolic) trajectory model based
on Campana & Laumond (2016), "Ballistic motion planning":

    Eq. 4:  xdot(alpha) = sqrt( g * X^2 / (2 * (X * tan(alpha) - Z)) )
    Eq. 2:  z(u) = z_s + u * tan(alpha) - g * u^2 / (2 * xdot^2)

The energy chain
----------------
This robot HOPS rather than jumps: hops are not independent, because the
takeoff speed of one is set by the landing speed of the last. Flight is
lossless (`v_g^2 = v_s^2 - 2 g Z`), the stance phase returns a fixed fraction
`eta` of the arriving kinetic energy (`v_s = sqrt(eta) * v_g`), and the
propellers may then inject up to `e_inject_max` — but only ADD, never shed.

So the takeoff speed is bounded on BOTH sides by the previous hop, and since
`(X, Z, alpha)` determines `v_s` outright, that band is a band of takeoff
angles: every parabola below the one the incoming speed produces is
unreachable, and every parabola above what full thrust affords is too. On top
of it, `min_apex` requires a minimum fall from apex to landing, or the elastic
leg never compresses enough for the controller to register a stance phase.

Two consequences for the search: the state is `(cell, speed_bin)` rather than
`cell`, and among the surviving angles the planner flies the one needing the
least injected energy — energy spent now is energy the next hop lacks.

Robot model
-----------
The robot's center of mass (the point the parabola actually tracks) sits
`leg_length` above the contact foot. Arcs therefore start and end at
`terrain_z + leg_length`, and terrain is sampled across the body's full width,
not just along the centreline.

Collision geometry is a capsule from the foot to the CoM with three
independently-sized regions, not one uniform radius:

  * `robot_radius` — the CoM sphere (the robot's actual body, the widest part);
  * `leg_radius` — the leg-cylinder sides (much thinner than the body);
  * `foot_radius` — the hemispherical foot tip (slightly fatter than the leg).

  * **Stance** (`Map2D5.standable_mask`): sphere at CoM (`robot_radius`) + upper
    `1 - frac` of the leg-cylinder sides (`leg_radius`). Bottom `frac` (default
    1/3) is exempt so that modest graded slopes stay standable. No foot-tip
    component at stance — the foot is on the ground by definition.
  * **Flight** (`terrain_profile` / `clearance_for_alpha`): the full capsule —
    sphere (top hemisphere, `robot_radius`) + full cylinder (`leg_radius`) +
    bottom hemisphere at the foot (`foot_radius`), so terrain directly under
    the foot must clear the foot tip by `foot_radius + min_clearance_gate`.
    Endpoints (u=0, u=X) are stance configurations and are masked out;
    `standable_mask` gates them.

Clearance is a hard feasibility gate (`min_clearance_gate`), not a cost term:
a hop either has an arc that stays clear of the terrain or it does not exist.
"""

import heapq
import math
from typing import NamedTuple

import numpy as np

from map2d5 import Map2D5


# --------------------------------------------------------------------------- #
# Ballistic-trajectory primitives (pure functions, unit-testable in isolation)
# --------------------------------------------------------------------------- #

# Small angular slack to keep alpha strictly inside the open feasible interval
# and away from the singularities `X*tan(alpha) = Z` (xdot -> inf) and
# `cos(alpha) = 0` (v_s -> inf).
_ALPHA_EPS = 1e-6


#: Normal of perfectly level ground — the default when no terrain normal is
#: supplied. Gives `gamma = pi/2`, `delta = beta`, i.e. the textbook flat-ground
#: friction cone `alpha in [pi/2 - atan(mu), pi/2 + atan(mu)]`.
_FLAT_NORMAL = (0.0, 0.0, 1.0)


def inplane_friction_cone(
    n: tuple[float, float, float],
    theta: float,
    mu: float,
) -> tuple[float, float] | None:
    """Reduce a 3D Coulomb friction cone to a 2D wedge in the hop plane.

    A contact velocity does not slip iff it lies within the cone of half-angle
    `beta = atan(mu)` around the surface normal `n`. The whole parabola lives in
    the vertical plane through the hop heading `theta`, so only that cone's
    intersection with the plane matters — itself an angular wedge, returned as
    `(gamma, delta)`: axis direction and half-angle, both measured in-plane from
    the horizontal.

    Campana & Laumond state this reduction (Sec. IV-A) but omit the formula for
    `delta` (their footnote 1). It is the standard cone/plane intersection: with
    `n_xt` the normal's component along the in-plane horizontal axis and `A` the
    length of the normal's projection into the plane,

        gamma = atan2(n_z, n_xt)
        A     = hypot(n_xt, n_z)          <= 1, since `n` also has an
                                          out-of-plane component
        delta = acos(cos(beta) / A)       <= beta, matching the paper's
                                          stated property

    Returns `None` when `cos(beta) / A > 1`: the plane then touches the cone
    only at its apex, so the wedge degenerates to a single direction and no jump
    is possible at this contact (paper, Fig. 1). Concretely this is what
    happens on a cross-slope steeper than `mu` — a surface the robot could not
    stand on without sliding.

    `gamma` is always in `(0, pi)` for terrain from a 2.5D grid, because
    `Map2D5.surface_normals` always yields `n_z > 0`. `_landing_cone_alpha_s`
    relies on that.
    """
    n_xt = n[0] * math.cos(theta) + n[1] * math.sin(theta)
    n_z = n[2]

    A = math.hypot(n_xt, n_z)
    if A < 1e-12:
        return None  # normal perpendicular to the hop plane — no usable wedge

    c = math.cos(math.atan(mu)) / A
    if c > 1.0:
        return None  # degenerate: plane meets the cone only at the apex
    return math.atan2(n_z, n_xt), math.acos(min(1.0, max(-1.0, c)))


def _speed_tan_interval(
    X: float,
    Z: float,
    W: float,
    g: float,
) -> tuple[float, float] | None:
    """`tan(alpha_s)` interval satisfying the takeoff-speed bound `v_s^2 <= W`.

    Substituting Campana Eq. 4 into `v_s = xdot / cos(alpha)` and writing
    `T = tan(alpha_s)` gives `v_s^2 = g X^2 (1 + T^2) / (2 (X T - Z))`, so
    `v_s^2 <= W` is the quadratic

        g X^2 T^2  -  2 W X T  +  (g X^2 + 2 W Z)  <=  0

    whose roots are `T = (W +- sqrt(D)) / (g X)` with
    `D = W^2 - g^2 X^2 - 2 g Z W`. A negative `D` means no angle meets the
    bound.

    One helper covers **both** of Campana's velocity constraints, because
    energy conservation on the CoM gives `v_g^2 = v_s^2 - 2 g Z`:

        (3) takeoff, `v_s <= V_max`:  W = V_max^2
            -> D = V_max^4 - 2 g Z V_max^2 - g^2 X^2   (the paper's `Delta`)
        (4) landing, `v_g <= V_max`:  W = V_max^2 + 2 g Z
            -> D = V_max^4 + 2 g Z V_max^2 - g^2 X^2   (the paper's `Lambda`)

    Note these are `tan(alpha)` values, not angles — the caller must `atan`
    them. (`docs/alpha_range_campana.md` flags the paper's notation as
    ambiguous here; the derivation above settles it.)

    `W <= 0` (only reachable for constraint 4, on a drop so large that
    `2 g |Z|` alone exceeds the landing budget) returns `None`.
    """
    if W <= 0.0:
        return None
    D = W * W - g * g * X * X - 2.0 * g * Z * W
    if D < 0.0:
        return None
    s = math.sqrt(D)
    return (W - s) / (g * X), (W + s) / (g * X)


def _landing_cone_alpha_s(
    X: float,
    Z: float,
    gamma_g: float,
    delta_g: float,
) -> tuple[float, float] | None:
    """Landing non-sliding constraint, expressed as an interval on `alpha_s`.

    The robot arrives at the goal contact moving *into* the surface, so it is
    the reversed velocity `-v_g` that must lie inside the landing cone. In
    terms of the in-plane arrival angle `alpha_g` that reads

        alpha_g + pi  in  [gamma_g - delta_g, gamma_g + delta_g]

    Relating `alpha_g` to the takeoff angle: differentiating Campana Eq. 2 and
    substituting Eq. 4 (`g / xdot^2 = 2 (X tan(alpha_s) - Z) / X^2`) gives

        tan(alpha_g) = tan(alpha_s) - 2 (X tan(alpha_s) - Z) / X
                     = -tan(alpha_s) + 2 Z / X

    so `tan(alpha_s) = 2 Z / X - tan(alpha_g)`, a strictly **decreasing** map:
    the interval endpoints swap. (Note the sign of the `2 Z / X` term — it is
    positive. `docs/alpha_range_campana.md` transcribes it as negative, which
    only coincides when `Z = 0`; see that file's errata note.)

    Rather than the paper's Algorithm 1 case split on `sign(gamma_g)`, this
    clamps the `alpha_g` interval to the range a real descending parabola can
    actually produce, `(-pi/2, atan2(Z, X))`, and maps the endpoints. That
    subsumes the algorithm's `no_solution` / `undefined` branches, keeps `tan`
    finite, and needs no case split: `gamma_g` is always in `(0, pi)` for
    heightmap terrain, so only the paper's `gamma_g > 0` branch can ever occur.
    """
    gamma_r = gamma_g - math.pi  # reversed cone axis; in (-pi, 0)

    lo_g = max(gamma_r - delta_g, -0.5 * math.pi + _ALPHA_EPS)
    hi_g = min(gamma_r + delta_g, math.atan2(Z, X))
    if lo_g >= hi_g:
        return None

    k = 2.0 * Z / X
    return math.atan(k - math.tan(hi_g)), math.atan(k - math.tan(lo_g))


def min_apex_tan(X: float, Z: float, h_min: float) -> float | None:
    """Lower bound on `tan(alpha_s)` so the CoM falls at least `h_min` before landing.

    The mechanism needs a minimum DROP, not a minimum rise: the elastic leg has
    to compress enough for the controller to detect the stance phase, and what
    compresses it is the fall from the apex down to the landing contact. On an
    uphill hop the robot can rise 0.3 m and still land while barely descending,
    which is why this is measured apex -> landing rather than takeoff -> apex.

    Differentiating Campana Eq. 2 and substituting Eq. 4 gives the vertical
    velocity at landing,

        v_z_g = v_s cos(alpha) * (2 Z / X - tan(alpha))

    so the robot is descending at all only when `X tan(alpha) > 2 Z`. The fall
    from the apex is `h = v_z_g^2 / (2 g)`; substituting Eq. 4 once more clears
    `v_s` out of it entirely and leaves, with `T = tan(alpha)` and `s = X T - Z`,

        h_drop = (X T - 2 Z)^2 / (4 (X T - Z)) = (s - Z)^2 / (4 s)

    which has `d/ds = (s^2 - Z^2) / (4 s^2) >= 0` whenever `s >= |Z|` — and on
    the domain that matters (`T >= 0` and `X T > 2 Z`) that always holds. So
    `h_drop` is monotone in `T`, the constraint inverts to a single lower bound,
    and no bisection is needed:

        s = (Z + 2h) + 2 sqrt(h (h + Z))     ->     T = (s + Z) / X

    Returns `None` when the constraint is vacuous, i.e. `h_min + Z < 0`: the
    landing is already more than `h_min` below the takeoff, so even a horizontal
    launch drops far enough.

    Sanity check on level ground: `T = 4 h / X`, matching `apex = X tan(a) / 4`.
    """
    if X < 1e-9:
        return None
    w = h_min + Z
    if w < 0.0:
        return None  # the terrain drop alone already exceeds h_min
    return 2.0 * (Z + h_min + math.sqrt(h_min * w)) / X


def min_energy_tan(X: float, Z: float) -> float:
    """`tan(alpha_s)` of the cheapest parabola reaching `(X, Z)`.

    `v_s^2 = g X^2 (1 + T^2) / (2 (X T - Z))` is U-shaped in `T`: it blows up
    both as the angle flattens toward the chord (`X T -> Z`) and as it steepens
    toward vertical. Setting the derivative to zero gives `X T^2 - 2 Z T - X = 0`,
    whose positive root is below. On level ground it is `T = 1`, i.e. the
    textbook 45 degrees.

    This is the angle that minimises injected energy, so it is what
    `alpha_for_clearance` aims at — but note it is usually *outside* the feasible
    interval, below its floor, because the energy floor from the previous hop
    starts at the steep branch. It matters only when the incoming speed is too
    low to reach the target at all.
    """
    return (Z + math.hypot(Z, X)) / X


def takeoff_speed(X: float, Z: float, alpha_s: float, g: float) -> float:
    """CoM speed `v_s` needed to fly `(X, Z)` at takeoff angle `alpha_s`."""
    return _xdot(X, Z, alpha_s, g) / math.cos(alpha_s)


def landing_speed(v_s: float, Z: float, g: float) -> float:
    """CoM speed at touchdown. Flight is lossless, so `v_g^2 = v_s^2 - 2 g Z`.

    Both ends of the arc sit at `terrain + leg_length`, so the leg offset
    cancels and `Z` is the terrain elevation change. Climbing costs speed,
    dropping gains it.
    """
    return math.sqrt(max(0.0, v_s * v_s - 2.0 * g * Z))


def injection_energy(v_s: float, v_s_min: float, mass: float) -> float:
    """Energy the propellers must add to reach `v_s` from a `v_s_min` stance exit."""
    return 0.5 * mass * max(0.0, v_s * v_s - v_s_min * v_s_min)


def max_hop_radius(
    v_g_in: float, eta: float, e_inject_max: float, mass: float, g: float,
    V_max: float,
) -> float:
    """Farthest flat-ground hop reachable at 45 deg, the min-energy angle.

    `v_s_max` is the ceiling the energy chain allows for this hop: the
    unshedable floor `sqrt(eta) * v_g_in` plus one full injection cycle,
    capped at `V_max` (mirrors `feasible_alpha_interval`'s E2 ceiling). At
    45 degrees Campana Eq. 4 reduces to the textbook range formula
    `X = v_s^2 / g` (`min_energy_tan` already identifies 45 deg as the
    min-energy angle on flat ground). This is what sizes the neighbor-
    generation ring per state — see `_generate_hop_neighbors`.
    """
    v_s_min = math.sqrt(eta) * v_g_in
    v_s_max = math.sqrt(min(
        v_s_min * v_s_min + 2.0 * e_inject_max / mass, V_max * V_max,
    ))
    return v_s_max * v_s_max / g


# --------------------------------------------------------------------------- #
# Takeoff-interval instrumentation (DIAGNOSTIC ONLY, and removable as a unit —
# see `feasible_alpha_interval`'s `trace` parameter for how to strip it).
# --------------------------------------------------------------------------- #

#: The constraints `feasible_alpha_interval` intersects, in the order it applies
#: them, with which end each one can move. Consumers iterate this rather than
#: hard-coding the list, so a new constraint shows up in the diagnostics
#: automatically instead of being silently omitted.
_TRACE_STEPS: tuple[tuple[str, str], ...] = (
    ("E1_energy_floor",   "(E1) energy floor — unshedable arrival speed"),
    ("E2_inject_ceiling", "(E2) injection ceiling — one thrust cycle"),
    ("E3_min_apex",       "(E3) minimum apex-to-landing drop"),
    ("c4_landing_speed",  "(4) landing speed <= V_g_max"),
    ("c1_takeoff_cone",   "(1) takeoff friction cone"),
    ("c2_landing_cone",   "(2) landing friction cone (mapped through the arc)"),
)


def _trace_add(
    trace: list,
    name: str,
    own_lo: float | None,
    own_hi: float | None,
    run_lo: float,
    run_hi: float,
    fatal: bool = False,
) -> None:
    """Record one constraint's own bound and what it actually cut.

    Called AFTER the constraint has been folded into `run_lo` / `run_hi`, so
    `cut_lo` and `cut_hi` are read off the difference against the previous
    record rather than recomputed — which is what keeps the trace honest even
    if a bound's formula changes.

    `own_lo`/`own_hi` are `None` for a one-sided constraint (E1 and E3 only
    raise the floor; E2 only lowers the ceiling) or for a constraint that was
    unsatisfiable, in which case `fatal` is set and the interval is empty.
    """
    prev_lo, prev_hi = (trace[-1]["run_lo"], trace[-1]["run_hi"]) if trace else (run_lo, run_hi)
    trace.append({
        "step": len(trace),
        "name": name,
        "own_lo": own_lo,
        "own_hi": own_hi,
        "run_lo": run_lo,
        "run_hi": run_hi,
        "cut_lo": max(0.0, run_lo - prev_lo),   # angle removed from below
        "cut_hi": max(0.0, prev_hi - run_hi),   # angle removed from above
        "fatal": fatal,
    })


def feasible_alpha_interval(
    X: float,
    Z: float,
    V_max: float,
    g: float,
    *,
    mu: float | None = 1.2,
    n_s: tuple[float, float, float] | None = None,
    n_g: tuple[float, float, float] | None = None,
    theta: float = 0.0,
    v_s_min: float,
    e_inject_max: float,
    mass: float,
    min_apex: float | None = None,
    V_g_max: float | None = None,
    trace: list | None = None,
) -> tuple[float, float] | None:
    """Feasible takeoff-angle interval [alpha_min, alpha_max] for a hop.

    Campana & Laumond's BEAM, plus this robot's energy chain. Given `X` and `Z`,
    choosing `alpha` fixes the parabola completely, so every constraint reduces
    to an interval on `alpha`. Arc height is monotone increasing in `tan(alpha)`
    (see `alpha_for_clearance`), so "higher parabola" and "larger alpha" are the
    same statement and every constraint below is literally a bound on how high
    the arc may be.

    The energy constraints are applied FIRST, because they are the ones that can
    wipe out most of the interval:

    (E1)  Energy floor. The robot arrives with a takeoff speed it cannot shed —
          propellers only ADD energy — so every parabola *below* the one
          `v_s_min` produces is unreachable, not merely suboptimal. Since
          `_speed_tan_interval` returns where `v_s^2 <= W`, the floor is the
          complement of that interval, which has two branches; we keep the
          upper one (the higher parabola). If `v_s_min` cannot reach `(X, Z)`
          at any angle the floor is vacuous and the lower bound falls back to
          (E2)'s own lower root.

    (E2)  Injection ceiling, `v_s <= sqrt(v_s_min^2 + 2 e_inject_max / mass)`,
          capped at `V_max`: the most one stance-plus-thrust cycle can produce,
          never more than the global worst case over every possible parent hop.
          The `min()` against `V_max` in its own computation makes it at least
          as tight as Campana's takeoff-speed constraint `v_s <= V_max`
          everywhere, which is why that constraint isn't applied separately
          below.

    (E3)  Minimum drop, `min_apex` — see `min_apex_tan`. A pure fallback: it is
          `max`ed against (E1), so it changes nothing unless the incoming speed
          produces a parabola that is *too low* to compress the leg.

    (E1) and (E2) also make Campana's Eq. 4 validity (`X*tan(alpha) - Z > 0`,
    i.e. "aim above the chord to the target") redundant rather than merely
    dominated: `_speed_tan_interval` derives its `tan(alpha)` roots from
    `g X^2 (1+T^2) = 2 W (X T - Z)`, and the left side is always positive, so
    ANY real root already forces `X T - Z > 0` on its own. That domain is a
    half-line in `T` (`T > Z/X`), so once both of E1/E2's endpoints satisfy it,
    everything between them does too — there is nothing left for a separate
    `atan2(Z, X)` bracket to cut.

    Then Campana's remaining two:

    (1)   Takeoff non-sliding: the takeoff direction *is* `alpha_s`, so the
          friction wedge at the start contact applies directly —
          `alpha in [gamma_s - delta_s, gamma_s + delta_s]`.

    (2)   Landing non-sliding: see `_landing_cone_alpha_s`.

    (4)   Landing speed, `v_g <= V_g_max` — the leg must absorb the arrival as
          well as produce the departure. Since `v_g^2 = v_s^2 - 2 g Z`, this is
          slack on uphill hops and tight on downhill ones. This is the cap that
          does real work: it is what stops the robot dropping off something
          taller than it can land from.

    (4), (E1) and (E2) all share `_speed_tan_interval`; (1) and (2) share
    `inplane_friction_cone`.

    Parameters
    ----------
    mu : friction coefficient. `None` disables constraints (1) and (2) entirely
        — for A/B baselines that isolate what the friction cone contributes.
        Do NOT use `None` for real planning; the remaining constraints still
        apply.
    n_s, n_g : outward unit surface normals at the takeoff and landing contacts,
        from `Map2D5.surface_normals()`. Default to level ground.
    theta : hop heading, `atan2(dy, dx)`. Only the normals' components in the
        hop plane matter, and `theta` is what defines that plane; it is
        irrelevant when both normals are vertical.
    v_s_min, e_inject_max, mass : the energy band (E1)+(E2), required together.
        There is no bare-BEAM fallback mode: Campana's Eq. 4 and takeoff-speed
        constraints are folded into this band rather than kept as a separate
        code path (see the (E1)/(E2) notes above), so a caller with no energy
        state to supply cannot use this function.
    min_apex : (E3). `None` skips it.
    V_g_max : landing-speed cap for (4). Defaults to `V_max`, the pre-split
        behaviour where one speed capped both ends.
    trace : DIAGNOSTIC ONLY — pass a list and each constraint appends a record
        of its own bound and what it cut, as it is applied. See
        `_TRACE_STEPS` and `test/demo_takeoff_angle_range.py`. `None` (the
        default, and what the planner always passes) makes this inert: the
        arithmetic executed is identical either way, except for one extra
        `atan2` that seeds the trace's cut-accounting baseline and is
        otherwise skipped entirely.

        This instrumentation is deliberately REMOVABLE. Every added block is
        bracketed by `# --- trace ---` markers and either appends to `trace`
        or names an expression that was previously inlined into a `max`/`min`.
        To strip it: delete this parameter, delete every `# --- trace ---`
        block, and re-inline the named bounds. Nothing outside this function
        changes except its two diagnostic consumers.

    Returns the interval shrunk by `_ALPHA_EPS` at each end for numerical
    safety, or `None` if any constraint is unsatisfiable or the intersection is
    empty.
    """
    if X < 1e-9:
        # Degenerate horizontal displacement: not a real hop. The planner's
        # neighbour generator already dedups the current cell, so this is
        # defensive.
        return None

    if V_g_max is None:
        V_g_max = V_max

    # --- trace ---
    # Seed the trace's cut-accounting baseline with the geometric domain
    # (Campana Eq. 4 validity) so E1's cut_lo below reports correctly. Purely
    # bookkeeping for the diagnostic: E1/E2's own roots satisfy this domain on
    # their own (see docstring), so it is never applied to alpha_lo/alpha_hi,
    # and the atan2 call is skipped outright when trace is None (the planner's
    # hot path).
    if trace is not None:
        _trace_add(trace, "eq4_domain", math.atan2(Z, X), 0.5 * math.pi,
                   math.atan2(Z, X), 0.5 * math.pi)
    # --- end trace ---

    # (E1) energy floor and (E2) injection ceiling.
    W_lo = v_s_min * v_s_min
    # The ceiling is what one cycle can produce, never more than the global
    # worst case; min() also subsumes Campana's takeoff-speed bound (3).
    W_hi = min(W_lo + 2.0 * e_inject_max / mass, V_max * V_max)

    iv_hi = _speed_tan_interval(X, Z, W_hi, g)
    if iv_hi is None:
        # --- trace ---
        if trace is not None:
            _trace_add(trace, "E2_inject_ceiling", None, None,
                       math.atan2(Z, X), 0.5 * math.pi, fatal=True)
        # --- end trace ---
        return None  # unreachable even at full thrust
    iv_lo = _speed_tan_interval(X, Z, W_lo, g)
    # Upper branch of the floor when v_s_min can reach the target; when it
    # cannot, every angle already needs injection and the binding lower
    # bound is the ceiling interval's own lower root.
    alpha_lo = math.atan(iv_lo[1] if iv_lo else iv_hi[0])
    alpha_hi = math.atan(iv_hi[1])
    # --- trace ---
    if trace is not None:
        _trace_add(trace, "E1_energy_floor", alpha_lo, None, alpha_lo, alpha_hi)
        _trace_add(trace, "E2_inject_ceiling", None, alpha_hi, alpha_lo, alpha_hi)
    # --- end trace ---

    # (E3) Minimum apex-to-landing drop. A `max` against the energy floor, so it
    # only bites when the incoming speed's parabola is itself too low.
    if min_apex is not None:
        T_apex = min_apex_tan(X, Z, min_apex)
        e3_lo = None if T_apex is None else math.atan(T_apex)
        if e3_lo is not None:
            alpha_lo = max(alpha_lo, e3_lo)
        # --- trace ---
        if trace is not None:
            _trace_add(trace, "E3_min_apex", e3_lo, None, alpha_lo, alpha_hi)
        # --- end trace ---

    # (4) Landing speed, v_g <= V_g_max. (Campana's takeoff-speed constraint
    # (3) is subsumed by (E2) above, so it is not checked separately here.)
    tan_iv = _speed_tan_interval(X, Z, V_g_max * V_g_max + 2.0 * g * Z, g)
    if tan_iv is None:
        # --- trace ---
        if trace is not None:
            _trace_add(trace, "c4_landing_speed", None, None,
                       alpha_lo, alpha_hi, fatal=True)
        # --- end trace ---
        return None
    own_lo, own_hi = math.atan(tan_iv[0]), math.atan(tan_iv[1])
    alpha_lo = max(alpha_lo, own_lo)
    alpha_hi = min(alpha_hi, own_hi)
    # --- trace ---
    if trace is not None:
        _trace_add(trace, "c4_landing_speed", own_lo, own_hi, alpha_lo, alpha_hi)
    # --- end trace ---

    if mu is not None:
        # (1) Takeoff non-sliding — the wedge applies to alpha_s directly.
        cone_s = inplane_friction_cone(n_s if n_s is not None else _FLAT_NORMAL,
                                       theta, mu)
        if cone_s is None:
            # --- trace ---
            if trace is not None:
                _trace_add(trace, "c1_takeoff_cone", None, None,
                           alpha_lo, alpha_hi, fatal=True)
            # --- end trace ---
            return None
        alpha_lo = max(alpha_lo, cone_s[0] - cone_s[1])
        alpha_hi = min(alpha_hi, cone_s[0] + cone_s[1])
        # --- trace ---
        if trace is not None:
            _trace_add(trace, "c1_takeoff_cone", cone_s[0] - cone_s[1],
                       cone_s[0] + cone_s[1], alpha_lo, alpha_hi)
        # --- end trace ---

        # (2) Landing non-sliding — mapped back through the parabola.
        cone_g = inplane_friction_cone(n_g if n_g is not None else _FLAT_NORMAL,
                                       theta, mu)
        land_iv = (None if cone_g is None
                   else _landing_cone_alpha_s(X, Z, cone_g[0], cone_g[1]))
        if land_iv is None:
            # --- trace ---
            if trace is not None:
                _trace_add(trace, "c2_landing_cone", None, None,
                           alpha_lo, alpha_hi, fatal=True)
            # --- end trace ---
            return None
        alpha_lo = max(alpha_lo, land_iv[0])
        alpha_hi = min(alpha_hi, land_iv[1])
        # --- trace ---
        if trace is not None:
            _trace_add(trace, "c2_landing_cone", land_iv[0], land_iv[1],
                       alpha_lo, alpha_hi)
        # --- end trace ---

    alpha_min = alpha_lo + _ALPHA_EPS
    alpha_max = alpha_hi - _ALPHA_EPS

    if alpha_min >= alpha_max:
        # --- trace ---
        if trace is not None and trace:
            trace[-1]["fatal"] = True  # the last constraint applied is what emptied it
        # --- end trace ---
        return None
    return alpha_min, alpha_max


def _xdot(X: float, Z: float, alpha_s: float, g: float) -> float:
    """Horizontal takeoff velocity (Campana Eq. 4). Caller must ensure the
    denominator is strictly positive, i.e. `alpha_s > atan2(Z, X)`."""
    denom = 2.0 * (X * math.tan(alpha_s) - Z)
    return math.sqrt(g * X * X / denom)


def _arc_z(u, X: float, Z: float, z_s: float, alpha_s: float):
    """CoM height along the arc at horizontal traversal `u` (Campana Eq. 2).

    Uses the `xdot`-free form of Eq. 2. Substituting Eq. 4 gives
    `g / (2 * xdot^2) = (X * tan(alpha) - Z) / X^2`, so

        z(u) = z_s + u * tan(alpha) - ((X * tan(alpha) - Z) / X^2) * u^2

    which is algebraically identical but avoids both a `sqrt` and the
    `X*tan(alpha) - Z -> 0` singularity that `_xdot` has to guard against.
    `u` may be a numpy array, which is what makes the alpha sweep cheap.
    """
    tan_a = math.tan(alpha_s)
    k = (X * tan_a - Z) / (X * X)
    return z_s + u * tan_a - k * u * u


def predict_trajectory(
    c_s: tuple[float, float, float],
    c_g: tuple[float, float, float],
    alpha_s: float,
    leg_length: float = 0.0,
    n_samples: int = 32,
) -> list[tuple[float, float, float]]:
    """Sample the parabolic CoM arc from `c_s` to `c_g` with takeoff angle `alpha_s`.

    `c_s`/`c_g` carry *terrain* heights; the arc runs between
    `terrain + leg_length` at each end. Returns a list of `(x, y, z)` points
    whose XY projection is the straight segment from `c_s[:2]` to `c_g[:2]`.
    """
    x_s, y_s, t_s = c_s
    x_g, y_g, t_g = c_g

    dx = x_g - x_s
    dy = y_g - y_s
    X = math.hypot(dx, dy)
    if X < 1e-9 or n_samples < 2:
        return [c_s, c_g]

    theta = math.atan2(dy, dx)
    cos_t = math.cos(theta)
    sin_t = math.sin(theta)

    z_s = t_s + leg_length
    Z = t_g - t_s

    pts: list[tuple[float, float, float]] = []
    for i in range(n_samples):
        u = X * i / (n_samples - 1)
        z_u = _arc_z(u, X, Z, z_s, alpha_s)
        pts.append((x_s + u * cos_t, y_s + u * sin_t, z_u))
    return pts


class ArcProfile(NamedTuple):
    """Everything about a hop that does *not* depend on the takeoff angle.

    Terrain sampling is by far the expensive part of validating a hop, and the
    XY corridor the body sweeps is fixed by the endpoints alone — only the
    arc's height varies with alpha. Splitting the two lets a whole sweep of
    candidate angles reuse one terrain lookup (see `alpha_for_clearance`).

    Terrain is stored **per (u, lateral offset) sample** — no max collapse —
    because the capsule clearance check needs both the lateral offset `r` and
    the terrain height at that offset. Collapsing to max terrain per `u`
    (as the old sphere-only check did) throws away `r` and cannot express the
    foot bottom-cap.
    """
    u: np.ndarray            # horizontal traversal samples, shape (n_u,)
    terrain: np.ndarray      # bilinear terrain, shape (n_u, n_lateral)
    offsets: np.ndarray      # signed lateral offsets, shape (n_lateral,)
    X: float                 # horizontal hop distance
    Z: float                 # terrain elevation change, z_g - z_s
    z_s: float               # CoM height at takeoff = terrain + leg_length
    com_radius: float        # CoM sphere radius (the robot's actual body)
    leg_radius: float        # leg-cylinder sides radius (thin)
    foot_radius: float       # foot-tip hemisphere radius (slightly fatter than leg)
    leg_length: float        # CoM height above the foot; foot_h = z_arc - L
    min_clearance_gate: float  # the gate the caller will compare mc against;
                               # used by clearance_for_alpha to size the
                               # endpoint-transition mask so mc doesn't stall
                               # at the mask boundary.
    out_of_bounds: bool      # centreline left the map -> hop is infeasible


def terrain_profile(
    c_s: tuple[float, float, float],
    c_g: tuple[float, float, float],
    height_map: Map2D5,
    com_radius: float,
    leg_radius: float,
    foot_radius: float,
    leg_length: float,
    max_step: float,
    obstacle_fill: float,
    n_lateral: int = 3,
    min_clearance_gate: float = 0.0,
) -> ArcProfile | None:
    """Sample the terrain under the corridor the robot's body sweeps.

    Marches the closed interval `u in [0, X]` in steps of
    `min(max_step, height_map.resolution / 3)`, so terrain is sampled at least
    ~3x per grid cell. At each `u`, `n_lateral` points spanning
    `[-(r_max + min_clearance_gate), +(r_max + min_clearance_gate)]`
    perpendicular to travel are sampled, where `r_max = max(com_radius,
    leg_radius, foot_radius)` — the CoM sphere in practice, since it's the
    widest part (`config.py` asserts `ROBOT_RADIUS` is the largest of the
    three). Terrain values are kept per-sample (no max collapse) because the
    capsule clearance check needs each sample's lateral offset independently
    — see `clearance_for_alpha`.

    The corridor half-width includes `min_clearance_gate` (not just `r_max`)
    so that terrain in the safety-margin band around the body is also
    detected. `min_clearance_gate=0` reduces to the old body-only corridor.

    OBSTACLE cells read as `obstacle_fill` (a tall-wall value) so they block
    arcs rather than producing bilinear artefacts.

    Sampling is closed rather than trimmed at the endpoints. The endpoint
    samples are stance configurations (foot on the ground) and are masked to
    `+inf` by `clearance_for_alpha`, so they never rejct a hop on their own —
    `standable_mask` is what gates stance at those points.

    Lateral samples are clamped to the map (bilinear degrades to nearest-edge)
    rather than failing the hop, so a body passing near the border does not
    delete an `r_max`-wide ring of the map. Only the centreline leaving the
    map marks the hop infeasible.

    Returns `None` for a degenerate zero-length hop.
    """
    x_s, y_s, t_s = c_s
    x_g, y_g, t_g = c_g

    dx = x_g - x_s
    dy = y_g - y_s
    X = math.hypot(dx, dy)
    if X < 1e-9:
        return None

    theta = math.atan2(dy, dx)
    cos_t = math.cos(theta)
    sin_t = math.sin(theta)

    step = min(max_step, height_map.resolution / 3.0)
    n = max(3, int(math.ceil(X / step)) + 1)
    u = np.linspace(0.0, X, n)

    cx = x_s + u * cos_t
    cy = y_s + u * sin_t

    out_of_bounds = bool(
        np.any((cx < 0.0) | (cx >= height_map.size_x)
               | (cy < 0.0) | (cy >= height_map.size_y))
    )

    corridor_half_width = max(com_radius, leg_radius, foot_radius) + min_clearance_gate
    if n_lateral <= 1:
        offsets = np.zeros(1)
    else:
        offsets = np.linspace(-corridor_half_width, corridor_half_width, n_lateral)

    # Perpendicular to travel is (-sin_t, cos_t).
    px = cx[:, None] - offsets[None, :] * sin_t
    py = cy[:, None] + offsets[None, :] * cos_t

    z = height_map.sample_bilinear(px, py, obstacle_fill=obstacle_fill)

    return ArcProfile(
        u=u,
        terrain=z,
        offsets=offsets,
        X=X,
        Z=t_g - t_s,
        z_s=t_s + leg_length,
        com_radius=com_radius,
        leg_radius=leg_radius,
        foot_radius=foot_radius,
        leg_length=leg_length,
        min_clearance_gate=min_clearance_gate,
        out_of_bounds=out_of_bounds,
    )


def clearance_for_alpha(profile: ArcProfile, alpha_s: float) -> float:
    """Minimum body-to-terrain clearance over a profile at one takeoff angle.

    Models the robot in flight as a **capsule** with axis from the foot
    (`foot_h = arc_z - leg_length`) to the CoM (`arc_z = z_arc`), covering
    three collision regions, each with its own radius:

      * top hemisphere at the CoM, radius `com_radius` — the robot's actual
        body, the widest part;
      * cylinder sides along the leg, radius `leg_radius` — much thinner;
      * bottom hemisphere at the foot, radius `foot_radius` — ensures terrain
        directly under the foot must clear the foot tip by
        `foot_radius + clearance`, not just `clearance`.

    Terrain is treated as a solid column (pillar) from the ground up to
    `h_terr`, the same convention `Map2D5.standable_mask` uses for its sphere
    check. For two vertical bars (the terrain pillar at offset `r` and the
    capsule's axis segment at offset 0), the distance between them is a
    geometry fact: if their height ranges overlap at all, the closest points
    are at the same height, so the distance is purely horizontal (`|r|`);
    only a genuine vertical gap (the pillar too short to reach the segment)
    produces a diagonal distance. Concretely, for a terrain sample at lateral
    offset `r` (signed) and height `h_terr`:

        h_terr < foot_h            : axis_dist = hypot(r, foot_h - h_terr)
                                      radius = foot_radius
                                      (pillar doesn't reach the foot -> a
                                       real gap -> bottom hemisphere nearest)
        foot_h <= h_terr <= z_arc  : axis_dist = |r|
                                      radius = leg_radius
                                      (pillar overlaps the leg's height range)
        h_terr > z_arc              : axis_dist = |r|
                                      radius = com_radius
                                      (pillar reaches past the CoM -> its
                                       material is also present at height
                                       z_arc itself -> top hemisphere nearest)

    Capsule clearance is `axis_dist - radius`. The min over all (u, r) samples
    is what the gate compares against.

    **Endpoint-transition mask**. Under a rigid-vertical-leg flight model,
    samples near u=0 and u=X have foot_h very close to the endpoint terrain
    (arc rises quadratically from the takeoff CoM), so a naive bottom-cap
    check would report the foot skimming ground and reject every hop.
    `standable_mask` already validates stance at both endpoints, so this
    function masks samples where the sample terrain is at-or-below the taller
    endpoint AND the foot has not yet risen a full `foot_radius` above that
    endpoint. Walls (terrain > endpoint_max) are never masked — the arc must
    still clear them meaningfully.

    Monotonicity in `tan(α)`: raising α lifts `arc_z(u)` (and therefore
    `foot_h`) at every interior `u` by the same amount (they're a fixed
    `leg_length` apart). For a fixed terrain sample, this only ever pushes it
    in one direction through the three cases above — never backwards — and at
    each such crossing the radius can only shrink (`com_radius -> leg_radius`,
    or the pre-existing case where the below-foot `delta` grows), so capsule
    clearance is monotone nondecreasing in `tan(α)` overall, and
    `alpha_for_clearance`'s bisection remains valid. The one exception is the
    exact `h_terr == foot_h` crossing, where the radius switches from
    `leg_radius` to the (larger) `foot_radius` — a discontinuous, sub-
    centimeter *decrease* in clearance right at that single crossing, far
    below `min_clearance_gate` and not worth correcting with true nearest-
    point-on-cone geometry.

    This is the cheap half of the split: a handful of vectorized ops on an
    array that `terrain_profile` already paid for.
    """
    if profile.out_of_bounds:
        return -math.inf
    z_arc = _arc_z(profile.u, profile.X, profile.Z, profile.z_s, alpha_s)
    foot_h = z_arc - profile.leg_length  # shape (n_u,)
    # below_foot > 0 -> terrain below the foot (bottom-cap region);
    # below_foot <= 0 -> terrain reaches foot height or above (leg / CoM region).
    below_foot = foot_h[:, None] - profile.terrain  # shape (n_u, n_lateral)
    above_com = profile.terrain - z_arc[:, None]    # > 0 -> terrain above the CoM
    r_abs = np.abs(profile.offsets)[None, :]        # shape (1, n_lateral)
    axis_dist = np.where(
        below_foot > 0.0,
        np.hypot(r_abs, below_foot),
        r_abs + np.zeros_like(below_foot),  # broadcast to full shape
    )
    radius = np.where(
        below_foot > 0.0, profile.foot_radius,
        np.where(above_com > 0.0, profile.com_radius, profile.leg_radius),
    )
    capsule_clearance = axis_dist - radius
    # Endpoint-transition mask. Near takeoff and landing the rigid-vertical-leg
    # model reports the foot grazing endpoint terrain (foot_h ≈ terrain → tiny
    # below_foot → tiny axis_dist → spurious fail). `standable_mask` has
    # already validated stance there. Mask samples where BOTH:
    #   (a) the terrain at this sample is at or below the taller endpoint's
    #       terrain — so this isn't a wall, and
    #   (b) the foot has not yet risen a full `foot_radius + gate` above the
    #       taller endpoint's terrain — so we're still in the takeoff/landing
    #       transition where the real leg is retracted, not extended.
    # The `+ gate` term is what stops mc from stalling at the mask boundary:
    # without it, the first sample past `foot_h = endpoint_max + foot_radius`
    # would give `capsule_clear ≈ 0 < gate` and drag mc down to zero regardless
    # of what the real flight-portion of the arc looks like.
    # Walls (terrain above endpoint_max) are never masked — the arc must
    # actually clear them. Endpoint rows (u=0, u=X) are subsumed by this mask
    # because `foot_h = t_s` and `foot_h = t_g` there.
    t_s = profile.z_s - profile.leg_length
    t_g = t_s + profile.Z
    endpoint_max = max(t_s, t_g)
    near_endpoint_terrain = profile.terrain <= endpoint_max + 1e-9
    lift_threshold = endpoint_max + profile.foot_radius + profile.min_clearance_gate
    foot_low = (foot_h < lift_threshold)[:, None]
    capsule_clearance = np.where(
        near_endpoint_terrain & foot_low, np.inf, capsule_clearance,
    )
    return float(np.min(capsule_clearance))


def min_clearance(
    c_s: tuple[float, float, float],
    c_g: tuple[float, float, float],
    alpha_s: float,
    height_map: Map2D5,
    com_radius: float,
    leg_radius: float,
    foot_radius: float,
    leg_length: float,
    max_step: float,
    obstacle_fill: float,
    n_lateral: int = 3,
    min_clearance_gate: float = 0.0,
) -> float:
    """Minimum body-to-terrain clearance over the hop.

    Convenience wrapper: `terrain_profile` followed by `clearance_for_alpha`.
    Use the two directly when evaluating several angles over one hop.

    Returns `-inf` if the arc leaves the map, `+inf` for a degenerate
    zero-length hop. Note there is no `g` parameter — the closed form in
    `_arc_z` does not need one.
    """
    profile = terrain_profile(
        c_s, c_g, height_map, com_radius, leg_radius, foot_radius, leg_length,
        max_step, obstacle_fill, n_lateral,
        min_clearance_gate=min_clearance_gate,
    )
    if profile is None:
        return math.inf
    return clearance_for_alpha(profile, alpha_s)


def alpha_for_clearance(
    profile: ArcProfile,
    alpha_min: float,
    alpha_max: float,
    gate: float,
    n_bisect: int = 8,
) -> tuple[float, float]:
    """Pick the takeoff angle needing the least injected energy that still clears.

    Returns `(alpha_s, clearance)`. The caller rejects the hop when the
    returned clearance is below `gate`.

    Two monotonicity facts make this exact rather than a search.

    Clearance is monotone nondecreasing in `tan(alpha)`: from `_arc_z`,
    `dz/d(tan a) = u * (X - u) / X >= 0` for every `u` in `[0, X]`, so a
    steeper angle lifts the whole arc at once and never trades height at one
    point for height at another. The pointwise minimum inherits that, so the
    set of clearing angles is always an upward-closed interval
    `[alpha_c, alpha_max]` — which makes `alpha_c` both unique and bisectable.

    Required speed, meanwhile, is U-shaped in alpha with its minimum at
    `min_energy_tan` — so the least-injection angle over `[alpha_c, alpha_max]`
    is exactly `clamp(alpha*, alpha_c, alpha_max)`, no search needed.

    In practice the clamp almost always returns `alpha_c` itself: `alpha*` sits
    below `alpha_min` whenever the previous hop's energy floor is binding, since
    that floor starts at the steep branch above the minimum-energy angle. The
    clamp matters only when the incoming speed is too low to reach the target
    at all, where the floor goes vacuous and `alpha*` lands inside the interval.

    Cost: one clearance evaluation in the common case (`alpha_min` already
    clears), two on rejection, and the bisection only on genuinely tight hops.

    NOTE this replaced a max-margin-midpoint policy. The accept/reject verdict
    is identical either way — both reject only when even `alpha_max` fails —
    but the reported angle is now the shallowest sufficient one rather than the
    most comfortable one, because energy spent here is energy the *next* hop
    does not have.
    """
    alpha_c = alpha_min
    mc_c = clearance_for_alpha(profile, alpha_min)

    if mc_c < gate:
        mc_max = clearance_for_alpha(profile, alpha_max)
        if mc_max < gate:
            return alpha_max, mc_max  # no feasible angle clears

        lo, hi = alpha_min, alpha_max  # clears at hi, not at lo
        for _ in range(n_bisect):
            mid = 0.5 * (lo + hi)
            if clearance_for_alpha(profile, mid) >= gate:
                hi = mid
            else:
                lo = mid
        alpha_c, mc_c = hi, clearance_for_alpha(profile, hi)

    alpha_star = math.atan(min_energy_tan(profile.X, profile.Z))
    if alpha_star <= alpha_c:
        return alpha_c, mc_c
    alpha_s = min(alpha_star, alpha_max)
    return alpha_s, clearance_for_alpha(profile, alpha_s)


def clearance_floor_alpha(
    c_s: tuple[float, float, float],
    c_g: tuple[float, float, float],
    height_map: Map2D5,
    inflated_foot: np.ndarray,
    inflated_com: np.ndarray,
    leg_length: float,
    max_step: float,
) -> float | None:
    """Shallowest takeoff angle whose arc clears the terrain — in closed form.

    The configuration-space replacement for `terrain_profile` +
    `alpha_for_clearance`. Returns `alpha_c` in radians, `-inf` when nothing
    along the hop constrains the arc at all, or `None` when the centreline
    leaves the map. The caller still clamps into `[alpha_min, alpha_max]` and
    rejects when `alpha_c` exceeds `alpha_max` — this function knows nothing
    about the energy chain or the friction cones.

    Two facts make this exact rather than a search.

    **The robot is a point.** `Map2D5.inflated_field` has already baked the
    body's radii into the terrain, so the whole capsule test collapses to one
    scalar comparison per sample, against

        H(u) = max( inflated_foot(u),  inflated_com(u) - leg_length )

    `inflated_foot` carries the Pythagoras taper (the foot tip is a sphere);
    `inflated_com` does not, because `clearance_for_alpha`'s above-the-CoM
    branch treats such terrain as a full-height column. The leg-cylinder band
    needs no field of its own: `foot_radius + gate` exceeds `leg_radius + gate`
    at any sane geometry, so the foot field already forces terrain below the
    foot everywhere the leg check could fire. Only the CENTRELINE is sampled —
    the body's width is in the field, not in the sampling pattern, which is
    what removes the old `n_lateral` rake and its 15 cm gaps.

    **Arc height is linear in `tan(alpha)`.** From `_arc_z`, with the leg offset
    cancelled out so `foot_h(0) = t_s`,

        foot_h(u) = t_s + Z*u^2/X^2 + T * u*(X - u)/X       (T = tan alpha)

    so `foot_h(u) >= H(u)` inverts to a bound on `T` directly:

        T_req(u) = ( H(u) - t_s - Z*u^2/X^2 ) * X / ( u*(X - u) )

    and `alpha_c = atan(max_u T_req(u))`. One vectorized pass replaces the
    1.5-2.3 `clearance_for_alpha` calls and 8-step bisection this supersedes,
    and it yields the exact crossover rather than a bracket around it.

    **The endpoint exemption**, which the old code expressed as an
    alpha-dependent mask, becomes alpha-FREE here: a sample whose terrain is at
    or below `max(t_s, t_g)` can never reject the hop. Either the old mask
    covered it, or the foot had already risen a full `foot_radius + gate` above
    it, which puts it in the bottom-cap branch with clearance to spare. So only
    terrain strictly above BOTH endpoints constrains anything — tested as
    `inflated_com(u) > max(t_s, t_g)`, which holds exactly when some terrain
    within the CoM reach of `u` is above that height. Consequence worth
    knowing: a hop up onto a step, or down off one, is unconstrained by
    clearance no matter how big the step, because nothing en route is above both
    ends. Only genuine walls bite.

    `u = 0` and `u = X` are excluded (zero denominator). They are stance
    configurations, and `Map2D5.standable_mask` gates them — the same division of
    labour `clearance_for_alpha` documents. **Do not try to check them here with
    the fields instead.** An inflated field is a DISC, so at `u = 0` it also sees
    terrain *behind* the takeoff, which the reference's corridor never samples;
    on a graded map that is fatal rather than merely conservative. On
    `maps/slope_crest.py`'s 0.35 ramp the ground 0.24 m uphill sits 0.084 m above
    the foot, so an endpoint test rejected every hop off every ramp cell and
    `plan()` returned `None` straight from the start state.

    **The sampling step is not a free knob.** `T_req` has a POLE at each end (the
    `u*(X-u)` denominator), so it is far more sensitive to sample spacing near
    the endpoints than the fields themselves are — the fields are smooth at the
    scale of their own dilation radius, which is misleading here. Measured across
    the deck, marching at `resolution` lets 333 hops through that
    `clearance_for_alpha` rejects, `resolution/2` lets 20 through, and
    `resolution/3` — the density `terrain_profile` itself uses — lets none. Hence
    the clamp below. The win over the old check is dropping the lateral rake and
    the bisection, not a coarser march.
    """
    x_s, y_s, t_s = c_s
    x_g, y_g, t_g = c_g

    dx = x_g - x_s
    dy = y_g - y_s
    X = math.hypot(dx, dy)
    if X < 1e-9:
        return None

    # Matches `terrain_profile`'s density, and that is NOT a free knob: see the
    # docstring's note on the pole at u -> 0, X.
    step = min(max_step, height_map.resolution / 3.0)
    n = max(3, int(math.ceil(X / step)) + 1)
    u = np.linspace(0.0, X, n)

    cx = x_s + u * (dx / X)
    cy = y_s + u * (dy / X)
    if np.any((cx < 0.0) | (cx >= height_map.size_x)
              | (cy < 0.0) | (cy >= height_map.size_y)):
        return None

    res = height_map.resolution
    ci = (cx / res).astype(np.int64)
    ri = (cy / res).astype(np.int64)
    np.clip(ci, 0, height_map.cols - 1, out=ci)
    np.clip(ri, 0, height_map.rows - 1, out=ri)

    f_com = inflated_com[ri, ci]
    H = np.maximum(inflated_foot[ri, ci], f_com - leg_length)

    # Only terrain above BOTH endpoints can reject the hop — see the docstring.
    active = f_com > max(t_s, t_g)
    active[0] = False       # stance configurations; standable_mask gates these
    active[-1] = False
    if not active.any():
        return -math.inf

    ua = u[active]
    Z = t_g - t_s
    numer = H[active] - t_s - Z * (ua * ua) / (X * X)
    denom = ua * (X - ua) / X
    return float(math.atan(float(np.max(numer / denom))))


class HoppingAStarPlanner:
    """A* planner for a hopping robot on a 2.5D grid map.

    Every expansion generates candidate landing cells by densely filling a
    disk around the current cell with a `hop_scan_step`-spaced lattice (a
    scanline circle fill — see `_generate_hop_neighbors`). The disk's radius
    is derived fresh each expansion from the state's arrival speed
    (`max_hop_radius`) rather than fixed, since how far the robot CAN hop
    depends on the energy it is carrying. A hop is accepted only when a
    ballistic (parabolic) arc exists that:

      * fits the ENERGY BAND the previous hop leaves behind — at least the
        speed stance returns (`sqrt(eta) * v_g`, which the robot cannot shed),
        at most that plus one cycle's `e_inject_max`;
      * drops at least `min_apex` from its own apex, or the elastic leg never
        compresses enough for the controller to register a stance phase;
      * satisfies the Coulomb friction cone at both the takeoff and landing
        contacts, and `v_g <= V_g_max` (the fastest touchdown the leg can
        absorb) — Campana's Eq. 4 validity and takeoff-speed bound are implied
        by the energy band above rather than checked separately (see
        `feasible_alpha_interval`);
      * keeps the robot's body at least `min_clearance_gate` clear of the
        terrain across the whole corridor it sweeps.

    Because the first two depend on how the robot ARRIVED, the search state is
    `(cell, speed_bin)`, not `cell`. This is what makes it a hopping robot
    rather than a jumping one: the same cell reached two different ways is two
    different situations, and one of them may have no feasible continuation.

    Neither more nor less energy dominates — more raises the floor and shuts off
    shallow hops, less lowers the ceiling — so there is no valid dominance
    pruning, and the speed axis is quantised (`speed_bin`) instead. In practice
    the chain converges to a fixed point within ~3 hops, so few bins per cell
    stay live.

    Among the angles that survive every gate, the planner flies the one needing
    the LEAST injected energy (`alpha_for_clearance`), because energy spent on
    this hop is energy the next hop does not have.

    Clearance is a pure feasibility gate — it does not shape cost. Edge cost is
    `xy distance + w_energy * (injected energy + momentum thrown away)`, which
    replaced an elevation penalty that could not price the manoeuvre it was
    written for (see `_edge_cost`). The A* heuristic remains Euclidean XY
    distance to the goal, and stays admissible because both energy terms are
    non-negative and so only ever add to the actual cost — though note the
    heuristic cannot SEE them, which is what makes `w_energy` a search-speed
    dial as well as a behaviour one.

    A "goal-snap" edge is added whenever the goal lies within the current
    state's dynamic hop radius, so the planner can land exactly on the goal
    without needing a ring sample to happen to align with it.
    """

    def __init__(
        self,
        map_env: Map2D5,
        start: tuple[float, float],
        goal: tuple[float, float],
        max_jump_height: float = 0.5,
        # Exchange rate between energy and distance in the edge cost, m per J.
        # Derived rather than tuned — see `config.W_ENERGY` and `_edge_cost`.
        w_energy: float = 0.84,
        # Ballistic / clearance parameters (defaults match config.py).
        g: float = 9.81,
        # Global worst-case takeoff speed — a backstop, not the per-hop cap.
        # The per-hop ceiling comes from the parent's energy plus one cycle of
        # injection; see the energy parameters below.
        V_max: float = 7.345,
        # Energy chain. `mass`/`eta`/`e_inject_max` define the stance loss and
        # the thrust budget; `min_apex` the stance-detection floor; `h_initial`
        # seeds the chain at the start cell; `V_g_max` is the fastest touchdown
        # the leg can absorb, and the cap that actually gates real hops.
        mass: float = 0.8,
        eta: float = 0.7,
        e_inject_max: float = 7.848,
        min_apex: float = 0.3,
        h_initial: float = 1.0,
        V_g_max: float = 7.004,
        # Quantisation of the landing-speed axis of the search state. Too coarse
        # and the propagated energy drifts from the arc actually flown; too fine
        # and the state space multiplies for no modelling gain.
        speed_bin: float = 0.25,
        # Coulomb friction coefficient (Campana's BEAM constraints 1 and 2).
        # `None` drops the two friction-cone constraints — an A/B baseline knob
        # only, like `disable_clearance`; the Eq. 4 and leg-energy gates stay.
        mu: float | None = 1.2,
        robot_radius: float = 0.15,
        leg_radius: float = 0.01,
        foot_radius: float = 0.02,
        leg_length: float = 0.4,
        min_clearance_gate: float = 0.15,
        arc_max_step: float = 0.05,
        n_lateral: int = 3,
        obstacle_wall_extra: float = 1.5,
        # Fraction of `leg_length` (measured from the foot upward) that the
        # stance-time leg-cylinder-sides check ignores. The bottom `frac` of
        # the leg is exempt from the check so that graded slopes stay standable
        # (a rigid vertical leg would otherwise reject every uphill neighbour
        # inside `leg_radius + min_clearance_gate`). See
        # `Map2D5.standable_mask` for the max-grade derivation.
        leg_clearance_start_frac: float = 1.0 / 3.0,
        # Lattice spacing of the scanline circle-fill that generates candidate
        # landing cells, in world metres, AT the reference radius
        # `hop_scan_step_ref_radius` below — not a flat spacing at every
        # radius; see that parameter for why. Deliberately independent of
        # `map_env.resolution`: tying it to the grid means refining the map
        # also multiplies the branching factor, which dominates the cost of
        # planning.
        hop_scan_step: float = 0.3,
        # Reference hop_radius at which `hop_scan_step` is the spacing
        # actually used. Above this radius the effective spacing widens as
        # `hop_scan_step * sqrt(hop_radius / hop_scan_step_ref_radius)`, so
        # candidate count grows ~linearly with hop_radius (matching the old
        # ray-search's scaling) instead of the disk fill's naive ~quadratic
        # growth (disk area ~ hop_radius^2 at a flat spacing). Below this
        # radius the spacing is left at exactly `hop_scan_step` — never made
        # finer than configured. 1.0 m is the flat steady-state hop length
        # referenced throughout this codebase (see `config.W_ENERGY`'s
        # derivation), so ordinary hops are unaffected by this; only the rare
        # large-radius hops right after a big drop (up to ~5.5 m at
        # `config.V_MAX`) get coarsened, which is exactly where an
        # unscaled fill's cost blows up. Measured on stairs/tall_stairs/
        # slope_crest without this widening: the scanline fill ran 5.4-6.4x
        # slower than the old ray-search (up to 572.8s vs 94.1s per plan).
        # WITH it: 1.3-1.7x slower — the residual gap is the fill's inherently
        # higher candidate density even at/below the reference radius, not
        # further large-radius blowup.
        hop_scan_step_ref_radius: float = 1.0,
        # Inner radius of the annulus the scanline fill covers. 0 lets the
        # planner consider arbitrarily short hops; the energy cost makes more
        # hops more expensive.
        min_hop_radius: float = 0.0,
        # Demo/analysis flag: when True, skip the clearance gate entirely. The
        # BEAM feasibility gate and the standability check still run (they guard
        # physics and static pose, not arc clearance). Intended for A/B
        # baselines that isolate what the clearance gate contributes; do NOT use
        # for real planning. To isolate the friction cone instead, pass
        # `mu=None`.
        disable_clearance: bool = False,
        # Demo/analysis flag: when False, `_edge_cost` charges injected energy but
        # NOT the momentum a hop throws away. Third in the same family as
        # `disable_clearance` and `mu=None` — A/B baselines only.
        #
        # Unlike those two, this one is not merely a weaker model, it is a
        # KNOWN-BROKEN one, and worse than having no energy term at all. Short
        # hops need no thrust (the robot already carries the speed from its last
        # landing), so on injection alone they price as free and A* chops paths
        # into stubs that arrive drained — `[1.0, 1.0, 1.0]` at 3.16 m/s becomes
        # `[0.8, 1.0, 0.8, 0.4]` at 2.56 m/s. Do NOT reach for this as a way to
        # claw back planning time. See `test/demo_cost_model_ab.py`.
        charge_momentum: bool = True,
    ):
        self.map_env = map_env
        self.start_world = start
        self.goal_world = goal
        # Retained for backward compatibility, but the ballistic feasibility
        # gate below fully supersedes the old `|dz| <= max_jump_height` check.
        self.max_jump_height = max_jump_height
        self.w_energy = w_energy
        self.charge_momentum = charge_momentum

        # Ballistic parameters.
        self.g = g
        self.V_max = V_max
        self.mu = mu
        self.robot_radius = robot_radius
        self.leg_radius = leg_radius
        self.foot_radius = foot_radius
        self.leg_length = leg_length
        self.min_clearance_gate = min_clearance_gate
        self.arc_max_step = arc_max_step
        self.n_lateral = n_lateral
        self.leg_clearance_start_frac = leg_clearance_start_frac
        self.hop_scan_step = hop_scan_step
        self.hop_scan_step_ref_radius = hop_scan_step_ref_radius
        self.disable_clearance = disable_clearance

        # Energy chain.
        self.mass = mass
        self.eta = eta
        self.e_inject_max = e_inject_max
        self.min_apex = min_apex
        self.h_initial = h_initial
        self.V_g_max = V_g_max
        self.speed_bin = speed_bin

        # Virtual landing speed for the start cell, chosen so the uniform stance
        # rule `v_s = sqrt(eta) * v_g` reproduces a first takeoff speed of
        # `sqrt(2 g h_initial)` — the speed that lifts the CoM `h_initial`. The
        # first hop then needs no special case anywhere in the search.
        self.v_g_initial = math.sqrt(2.0 * g * h_initial / eta)

        # Height used in place of OBSTACLE sentinels when terrain is sampled
        # BILINEARLY. Setting it well above the tallest real cell makes OBSTACLE
        # cells act as un-flyable walls.
        #
        # No longer read by the planner itself: `Map2D5.inflated_field` gives
        # OBSTACLE cells `+inf` outright, which is strictly stronger and needs no
        # calibration against `MAX_APEX_HEIGHT`. It is kept because the reference
        # implementation (`terrain_profile`) needs it, and because most of
        # `test/demo_*.py` reads `planner._obstacle_fill` to reproduce what the
        # planner sees.
        non_obs = map_env.grid[map_env.grid != Map2D5.OBSTACLE]
        map_max_z = float(non_obs.max()) if non_obs.size > 0 else 0.0
        self._obstacle_fill = map_max_z + obstacle_wall_extra

        # Cells where the robot can physically stand. Screening landing cells
        # against this catches body-vs-terrain overlap for ~1us instead of
        # discovering the same collision by marching a whole arc.
        self._standable = map_env.standable_mask(
            robot_radius, leg_radius, min_clearance_gate, leg_length,
            leg_clearance_start_frac=leg_clearance_start_frac,
        )

        # Per-cell outward surface normals, for the friction cone at both
        # contact points. Like `_standable`, computed once and read per edge.
        self._normals = map_env.surface_normals()

        # Terrain inflated by the body, so the flight-clearance check can treat
        # the robot as a POINT (see `Map2D5.inflated_field` and
        # `clearance_floor_alpha`). Two fields, because the capsule's regions
        # have different radii AND different shapes: the foot tip is a sphere
        # (tapered), while terrain above the CoM is treated as a full-height
        # column by the reference check, so its field must NOT taper.
        #
        # This is what replaced per-hop terrain sampling. A profile was keyed on
        # a cell PAIR (~7M of them, hence a 60k FIFO cache running at a 17-34%
        # hit rate and re-reading each map cell ~62,000 times per plan); these
        # are keyed on a cell, so all 2500 answers are computed here, once, in
        # well under a millisecond.
        self._inflated_foot = map_env.inflated_field(
            foot_radius + min_clearance_gate, taper=True,
        )
        self._inflated_com = map_env.inflated_field(
            robot_radius + min_clearance_gate, taper=False,
        )

        # Convert start/goal to grid coordinates
        self.start_cell = map_env.world_to_grid(start[0], start[1])
        self.goal_cell = map_env.world_to_grid(goal[0], goal[1])

        # Inner radius of the scanline fill's annulus (see parameter docs above).
        self._min_hop_radius = min_hop_radius

        # Instrumentation counters, reset at the top of every plan() call.
        self.n_expansions = 0
        self.n_edge_checks = 0
        self.n_edges_accepted = 0

        # Per-hop record of the path plan() last returned; see `_reconstruct_path`.
        self.path_hops: list[dict] = []

    def _speed_bin(self, v_g: float) -> int:
        """Quantise a landing speed onto the state's speed axis."""
        return int(round(v_g / self.speed_bin))

    def plan(self) -> list[tuple[float, float]] | None:
        """Run A* and return the path as a list of (x, y) world coords, or None.

        Search states are `(cell, speed_bin)`: energy carries between hops, so a
        cell is not one node but one node per arrival speed. The canonical speed
        for a state is `speed_bin * self.speed_bin`, not the exact speed that
        produced it, which is what keeps the graph deterministic and finite.

        `self.path_hops` is populated with the per-hop physics of the returned
        path (angle, speeds, injection, apex drop).
        """
        goal = self.goal_cell

        # Instrumentation counters (reset per plan() call; see class docstring
        # users like test/benchmark_tall_stairs.py for how these are consumed).
        self.n_expansions = 0
        self.n_edge_checks = 0
        self.n_edges_accepted = 0
        self.path_hops = []

        start = (self.start_cell, self._speed_bin(self.v_g_initial))

        # Priority queue: (f_cost, counter, ((row, col), speed_bin))
        open_set = []
        counter = 0
        heapq.heappush(open_set, (0.0, counter, start))

        # g_cost[state] = best known cost from start to state
        g_cost = {start: 0.0}
        # came_from[state] = (parent state, the hop that got here)
        came_from: dict[tuple, tuple | None] = {start: None}

        while open_set:
            f, _, current = heapq.heappop(open_set)

            if current[0] == goal:
                return self._reconstruct_path(came_from, current)

            # Skip if we've already found a better path to this node
            if f > g_cost.get(current, float("inf")) + self._heuristic(current[0]):
                continue

            self.n_expansions += 1
            for neighbor, edge_cost, hop in self._generate_hop_neighbors(current):
                tentative_g = g_cost[current] + edge_cost

                if tentative_g < g_cost.get(neighbor, float("inf")):
                    g_cost[neighbor] = tentative_g
                    came_from[neighbor] = (current, hop)
                    f_cost = tentative_g + self._heuristic(neighbor[0])
                    counter += 1
                    heapq.heappush(open_set, (f_cost, counter, neighbor))

        return None  # No path found

    def _generate_hop_neighbors(
        self,
        state: tuple[tuple[int, int], int],
    ) -> list[tuple[tuple[tuple[int, int], int], float, dict]]:
        """Yield (neighbor_state, edge_cost, hop) triples reachable in one hop.

        The disk radius is not fixed: `max_hop_radius` derives it fresh from
        this state's arrival speed, as the flat-ground 45-degree range the
        robot's current energy (floor + one injection cycle) affords. Candidate
        landing cells are generated by a SCANLINE CIRCLE FILL: a `hop_scan_step`
        -spaced lattice centred on the current cell, walked one row (`y`) at a
        time, where each row's column span is bounded by the circle equation
        (`x_max = sqrt(reach^2 - y^2)`) rather than by a per-point distance
        test. Every point this produces is inside the disk by construction, so
        there is no discarded/wasted candidate the way a "walk the bounding
        square, reject the corners" version would have — and unlike a
        fixed-angle ray-search, spacing is uniform everywhere in the disk
        instead of dense near the centre and coarse at the rim.

        The lattice spacing itself is not flat across expansions: it is
        `hop_scan_step` up to `hop_scan_step_ref_radius`, then widens as
        `sqrt(hop_radius / hop_scan_step_ref_radius)` beyond it. A flat
        spacing fills a disk of area ~`hop_radius^2`, so candidate count would
        grow quadratically with hop_radius; widening the spacing this way
        keeps it growing ~linearly instead, matching how the old ray-search
        scaled, without sacrificing density at the common, small-radius case
        the reference is set to.

        Both bounds are padded by `step * sqrt(2) / 2` (half a lattice cell's
        diagonal), mirroring `Map2D5.inflated_field`'s `lookup_pad`: the outer
        bound is widened and the inner bound (`_min_hop_radius`, an annulus
        floor — 0 by default) is shrunk, so a cell the true circle merely
        TOUCHES is not excluded on a rounding technicality. Both moves are in
        the same "include more, not less" direction; an over-included
        candidate just fails `_validate_and_cost` like any other rejected cell,
        so there is no correctness cost to erring generous here.

        A "goal-snap" edge is also added whenever the goal lies within the
        computed radius, so the goal can be reached regardless of lattice
        alignment.

        The incoming speed is fixed for the whole expansion (it comes from
        `state`), so a single `attempted` set is enough to dedup: because the
        lattice sweep visits each snapped grid cell via one flat loop (not
        several independent rays that can converge on the same cell from
        different angles), a cell's validity never depends on which lattice
        point reached it first — `_validate_and_cost(current, current_z,
        neighbor, v_g_in)` is a pure function of those three arguments, all
        fixed for this expansion, so re-checking an already-attempted cell
        would only ever repeat the same answer.
        """
        current, v_bin = state
        v_g_in = v_bin * self.speed_bin
        hop_radius = max_hop_radius(
            v_g_in, self.eta, self.e_inject_max, self.mass, self.g, self.V_max,
        )

        cx, cy = self.map_env.grid_to_world(current[0], current[1])
        current_z = self.map_env.grid[current[0], current[1]]

        results: list[tuple[tuple[tuple[int, int], int], float, dict]] = []
        attempted: set[tuple[int, int]] = {current}

        # Lattice spacing, in world metres. Held at `hop_scan_step` up to
        # `hop_scan_step_ref_radius`, then widened as sqrt(hop_radius / ref)
        # so candidate count grows ~linearly with hop_radius (an area fill at
        # a FLAT spacing grows quadratically) — see the constructor param doc.
        step = self.hop_scan_step
        if hop_radius > self.hop_scan_step_ref_radius:
            step *= math.sqrt(hop_radius / self.hop_scan_step_ref_radius)
        pad = step * math.sqrt(2.0) / 2.0
        # Outer bound widened, inner bound shrunk — both moves make the swept
        # region strictly larger, never smaller (see docstring).
        reach = hop_radius + pad
        inner2 = max(0.0, self._min_hop_radius - pad) ** 2

        # Row by row, only the columns whose (x, y) can possibly lie in the
        # disk are ever visited — no point is generated outside it, so there
        # is nothing to discard after the fact. A very small `hop_radius`
        # (e.g. a near-zero incoming speed) still yields `reach = pad > 0`, so
        # a starved state gets a small ring of candidates rather than the
        # dead end a zero-radius ray-search would have produced; whether any
        # of them are actually reachable is still entirely up to
        # `_validate_and_cost`.
        iy_max = int(math.ceil(reach / step))
        for iy in range(-iy_max, iy_max + 1):
            y = iy * step
            rad2 = reach * reach - y * y
            if rad2 <= 0.0:
                continue
            ix_max = int(math.floor(math.sqrt(rad2) / step))
            for ix in range(-ix_max, ix_max + 1):
                x = ix * step
                if x * x + y * y < inner2:
                    continue

                tx = cx + x
                ty = cy + y
                if not self.map_env.is_within_bounds(tx, ty):
                    continue

                neighbor = self.map_env.world_to_grid(tx, ty)
                if neighbor in attempted:
                    continue
                attempted.add(neighbor)

                edge = self._validate_and_cost(
                    current, current_z, neighbor, v_g_in,
                )
                if edge is not None:
                    cost, hop = edge
                    hop["hop_radius"] = hop_radius
                    results.append(
                        ((neighbor, self._speed_bin(hop["v_g"])), cost, hop),
                    )

        # Goal-snap edge: allow landing exactly on the goal when it's in range.
        # Only attempt if the goal hasn't already been covered by the sweep.
        gx, gy = self.map_env.grid_to_world(self.goal_cell[0], self.goal_cell[1])
        if (
            np.hypot(gx - cx, gy - cy) <= hop_radius
            and self.goal_cell not in attempted
        ):
            edge = self._validate_and_cost(
                current, current_z, self.goal_cell, v_g_in,
            )
            if edge is not None:
                cost, hop = edge
                hop["hop_radius"] = hop_radius
                results.append(
                    ((self.goal_cell, self._speed_bin(hop["v_g"])), cost, hop),
                )

        return results

    def _validate_and_cost(
        self,
        current: tuple[int, int],
        current_z: float,
        neighbor: tuple[int, int],
        v_g_in: float,
    ) -> tuple[float, dict] | None:
        """Return `(edge_cost, hop)` if the hop is valid, else None.

        `v_g_in` is the speed at which the robot arrived at `current` — the
        whole reason this is a hopping planner and not a jumping one. It sets
        both ends of the takeoff-speed band: `sqrt(eta) * v_g_in` is the floor
        the robot cannot shed, and one cycle of `e_inject_max` on top of that is
        the ceiling.

        `hop` carries the physics of the flown arc back out (`alpha_s`, `v_s`,
        `v_g`, `e_inject`, `apex_drop`, ...); `v_g` is what the caller turns
        into the successor state's speed bin.

        Sequence, cheapest test first:
          (a) STANCE GATE: reject if the robot's body cannot sit at the landing
              cell without overlapping nearby terrain (precomputed mask); this
              also rejects OBSTACLE cells outright, since `standable_mask`
              never marks one standable;
          (b) FEASIBILITY GATE: reject if no `alpha_s` satisfies the energy band
              from `v_g_in`, the `min_apex` stance-detection floor, the
              friction cones at both contacts, and the landing-speed limit;
          (c) CLEARANCE GATE: solve for the shallowest takeoff angle whose arc
              keeps the body `min_clearance_gate` clear of the terrain
              (`clearance_floor_alpha`, reading the precomputed inflated
              fields), and reject if that exceeds `alpha_max`. Then fly the
              least-injection angle at or above it;
          (d) return the edge cost. Clearance does NOT appear here — it is a
              feasibility test, not a cost term. Injected energy DOES, together
              with the momentum the hop throws away; see `_edge_cost`. Note the
              two roles injection plays are distinct: step (c) minimises it
              *within* an edge (which angle to fly), while (d) prices it
              *across* edges (which hop to take).
        """
        self.n_edge_checks += 1
        neighbor_z = self.map_env.grid[neighbor[0], neighbor[1]]

        # (a) The robot must be able to stand where it lands. Also rejects
        # OBSTACLE cells: standable_mask ANDs in `grid != OBSTACLE` itself.
        if not self.disable_clearance and not self._standable[neighbor[0], neighbor[1]]:
            return None

        cx, cy = self.map_env.grid_to_world(current[0], current[1])
        nx, ny = self.map_env.grid_to_world(neighbor[0], neighbor[1])
        X = float(math.hypot(nx - cx, ny - cy))
        Z = float(neighbor_z - current_z)

        # (c) Energy band from the previous hop + min-apex floor + BEAM.
        v_s_min = math.sqrt(self.eta) * v_g_in
        interval = feasible_alpha_interval(
            X, Z, self.V_max, self.g,
            mu=self.mu,
            n_s=tuple(self._normals[current[0], current[1]]),
            n_g=tuple(self._normals[neighbor[0], neighbor[1]]),
            theta=math.atan2(ny - cy, nx - cx),
            v_s_min=v_s_min,
            e_inject_max=self.e_inject_max,
            mass=self.mass,
            min_apex=self.min_apex,
            V_g_max=self.V_g_max,
        )
        if interval is None:
            return None
        alpha_min, alpha_max = interval

        # (d) Arc-to-terrain clearance, read off the inflated fields. This is
        # also where the flown angle is chosen, so it must run even when the
        # gate is disabled — the successor's energy depends on it.
        alpha_floor = alpha_min
        if not self.disable_clearance:
            alpha_c = clearance_floor_alpha(
                (cx, cy, float(current_z)), (nx, ny, float(neighbor_z)),
                self.map_env,
                self._inflated_foot,
                self._inflated_com,
                self.leg_length,
                self.arc_max_step,
            )
            if alpha_c is None:
                return None  # the centreline leaves the map
            if alpha_c > alpha_max:
                return None  # no feasible arc clears the terrain
            alpha_floor = max(alpha_min, alpha_c)

        # Least-injection angle within what survives: required speed is U-shaped
        # in alpha with its minimum at `min_energy_tan`, so the cheapest angle in
        # `[alpha_floor, alpha_max]` is that minimum clamped into the interval.
        alpha_s = min(max(math.atan(min_energy_tan(X, Z)), alpha_floor), alpha_max)

        v_s = takeoff_speed(X, Z, alpha_s, self.g)
        v_g = landing_speed(v_s, Z, self.g)
        T = math.tan(alpha_s)
        hop = {
            "alpha_s": alpha_s,
            "v_s": v_s,
            "v_g": v_g,
            "v_g_in": v_g_in,
            "e_inject": injection_energy(v_s, v_s_min, self.mass),
            "apex_drop": (X * T - 2.0 * Z) ** 2 / (4.0 * (X * T - Z)),
            "X": X,
            "Z": Z,
        }

        self.n_edges_accepted += 1
        return self._edge_cost(current, neighbor, hop), hop

    def _edge_cost(
        self,
        current: tuple[int, int],
        neighbor: tuple[int, int],
        hop: dict,
    ) -> float:
        """Cost of hopping from `current` to `neighbor`, given the arc flown.

            cost = xy_dist + w_energy * (battery_used + momentum_thrown_away)

        This replaced an elevation penalty (`alpha_uphill * dz`), which could not
        do the job it was written for: arcing over a wall and landing at the same
        height is `dz = 0`, so it charged nothing for exactly the manoeuvre it was
        meant to price. It was also blind to how the robot ARRIVED, charging the
        same whether the hop was paid for with spare momentum or with thrust.

        **battery_used** is `hop["e_inject"]` — the propeller work this hop costs.
        It rises on its own when the clearance gate lifts `alpha` to clear
        terrain, which is what makes "over vs around" a physics question rather
        than a weight-tuning one. It also prices climbing (a hop to `Z = +0.4`
        needs 3.73 J against 1.20 J on the flat), which is why no separate
        elevation term is needed.

        **momentum_thrown_away** is `max(0, KE_in - KE_out)`, and without it the
        model is broken rather than merely incomplete. Short hops need no thrust
        — the robot already carries enough speed from the last landing — so on
        battery alone they look FREE, and A* chops the path into stubs. They are
        not free: every landing burns `1 - eta` of the kinetic energy, and the
        robot simply arrives drained. Summing `e_inject` counts the battery but
        not the bank account. This term bills the difference at exactly what
        buying that energy back would cost. Measured on `flat` at steady state,
        covering 1 m:

            one 1.0 m hop:   battery 1.20 J + momentum 0.00 J  =  1.20 J
            two 0.5 m hops:  battery 0.81 J + momentum 1.23 J  =  2.04 J

        It is ALSO what regulates hop count, which is why there is no per-hop
        energy constant here: holding speed steady costs
        `0.5 * mass * v^2 * (1 - eta)` per hop, an expression with no hop length
        in it, so N hops over the same ground cost N times as much. `min_apex`
        already makes very short hops expensive; this makes merely-shortish ones
        expensive too.

        `KE_out` uses the BINNED landing speed, not the exact `hop["v_g"]`.
        `hop["v_g_in"]` is already binned (see `_generate_hop_neighbors`) and the
        successor state carries the binned speed, so mixing binned-in with
        exact-out would leave up to ~0.32 J of quantisation noise per hop against
        a ~1.2 J signal.

        Both added terms are `>= 0` by construction (`injection_energy` clamps,
        and the `max(0, ...)` here), so `_heuristic` stays admissible and edge
        costs stay non-negative. The latter is not incidental: the uncapped form
        `e_inject + KE_in - KE_out` reaches -1.36 J on a 0.4 m drop, and negative
        edges break A*.

        Known conservatism: a climb converts kinetic energy into height rather
        than wasting it, but the momentum term charges for it anyway — about
        0.60 J on top of 3.72 J of real injection for a 0.4 m step.
        """
        cx, cy = self.map_env.grid_to_world(current[0], current[1])
        nx, ny = self.map_env.grid_to_world(neighbor[0], neighbor[1])
        xy_dist = float(np.hypot(nx - cx, ny - cy))

        e_momentum = 0.0
        if self.charge_momentum:  # False is an A/B baseline only — see __init__
            v_g_out = self._speed_bin(hop["v_g"]) * self.speed_bin
            ke_in = 0.5 * self.mass * hop["v_g_in"] ** 2
            ke_out = 0.5 * self.mass * v_g_out ** 2
            e_momentum = max(0.0, ke_in - ke_out)
            # e_momentum = ke_in * 0.3 # just trying a new way of keeping track

        return xy_dist + self.w_energy * (hop["e_inject"] + e_momentum)

    def _heuristic(self, cell: tuple[int, int]) -> float:
        """Admissible heuristic: Euclidean distance in world coordinates to goal.

        Admissible because sum of hop xy-distances >= straight-line distance
        (triangle inequality), and every other term in `_edge_cost` — the
        injected energy and the momentum charge — is non-negative, so it can
        only add to the actual g-cost.

        Admissible is not the same as INFORMED, and the gap matters here. This
        estimates distance only, so the whole energy term is cost the heuristic
        cannot anticipate; the larger `w_energy` is, the more A* degrades toward
        Dijkstra. Measured on `flat`, adding the energy term at `w_energy = 0.84`
        took expansions from 186 to ~1800. The known fix is a per-hop energy
        constant, which unlike the momentum charge can be lower-bounded from
        `ceil(remaining_distance / hop_radius)` and added here — though `hop_radius`
        is now state-dependent (`max_hop_radius`), not a single constant, so that
        bound would need the CURRENT state's radius, not a global one.
        """
        x1, y1 = self.map_env.grid_to_world(cell[0], cell[1])
        x2, y2 = self.map_env.grid_to_world(self.goal_cell[0], self.goal_cell[1])
        return float(np.hypot(x1 - x2, y1 - y2))

    def _reconstruct_path(
        self,
        came_from: dict[tuple, tuple | None],
        current: tuple,
    ) -> list[tuple[float, float]]:
        """Trace back from goal to start, return path in world coordinates.

        Also fills `self.path_hops` with the per-hop physics recorded at
        validation time. Callers that need the takeoff angle must read it from
        there rather than re-deriving it: with the energy chain, the angle
        depends on the whole path leading up to the hop, so it cannot be
        recovered from the endpoints alone.
        """
        path_cells = []
        hops = []
        while current is not None:
            path_cells.append(current[0])
            edge = came_from[current]
            if edge is None:
                break
            current, hop = edge
            hops.append(hop)
        path_cells.reverse()
        hops.reverse()

        self.path_hops = hops

        path = []
        for row, col in path_cells:
            x, y = self.map_env.grid_to_world(row, col)
            path.append((x, y))
        return path
